// Generated by research/ranking/check_fusion.mjs --export. Do not edit by hand.
// Physics-only retrospective calibration; prospective cross-field validation is pending.
export const FUSION_MODEL = {
  "version": 1,
  "receptionWeight": 4,
  "minimumAgeDays": 28,
  "sourceSha256": "7df944b502bd7b687b0e7e94ba9b0a87f202693254558ae5f8ea45657697eb32",
  "training": {
    "from": "1993-01",
    "to": "1995-12",
    "labelsCompleteBy": "1997-12",
    "grid": [
      {
        "weight": 1,
        "meanNdcg10": 0.6334645457632768
      },
      {
        "weight": 2,
        "meanNdcg10": 0.6403672117280043
      },
      {
        "weight": 4,
        "meanNdcg10": 0.6431982960910841
      }
    ]
  }
} as const;
