// Generated by research/ranking/export_model.py. Do not edit by hand.
//
// Weights apply to features rank-transformed to percentiles within the
// cohort. They were fitted with non-negative coefficients on pre-oriented
// signals, so no two can cancel and every paper's score decomposes into
// readable contributions. Regenerate after changing the feature set:
//
//   python research/ranking/export_model.py

import type { Signals } from "./signals.ts";

export type RankingModel = {
  version: number;
  note: string;
  trainedOn: {
    corpus: string;
    papers: number;
    positives: number;
    months: number;
    window: string;
  };
  validation: {
    protocol: string;
    auc: number;
    aucLow: number;
    aucHigh: number;
    liftAt10: number;
    liftAt25: number;
  };
  inputs: string;
  regularisation: { penalty: string; C: number };
  weights: Partial<Record<keyof Signals, number>>;
  /** [percentile, share of papers at that percentile that became references] */
  calibration: readonly (readonly [number, number])[];
  baseRate: number;
};

export const RANKING_MODEL = {
  "version": 1,
  "note": "Fitted by research/ranking/export_model.py. Do not hand-edit.",
  "trainedOn": {
    "corpus": "41k arXiv metadata sample, cs.LG / cs.CL / stat.ML listings",
    "papers": 6366,
    "positives": 87,
    "months": 11,
    "window": "2017-05 to 2018-03"
  },
  "validation": {
    "protocol": "leave-one-month-out",
    "auc": 0.7923,
    "aucLow": 0.757,
    "aucHigh": 0.8343,
    "liftAt10": 5.544,
    "liftAt25": 4.524
  },
  "inputs": "features rank-transformed to percentiles within the cohort",
  "regularisation": {
    "penalty": "l2",
    "C": 0.05
  },
  "weights": {
    "team_size": 0.35142,
    "author_new_frac": -1.17253,
    "author_degree_max": 0.57977,
    "author_recency": -1.41746,
    "author_reach": 1.0919,
    "n_categories": 0.0638,
    "title_words": -1.56018,
    "title_has_colon": 1.28441,
    "abstract_words": -0.76615,
    "has_named_system": 0.15943,
    "term_burst_mean": 0.53265,
    "term_rarity": -0.42667
  },
  "calibration": [
    [
      0.0,
      0.0
    ],
    [
      0.025,
      0.0
    ],
    [
      0.05,
      0.0
    ],
    [
      0.075,
      0.0
    ],
    [
      0.1,
      0.0
    ],
    [
      0.125,
      0.0
    ],
    [
      0.15,
      0.001556
    ],
    [
      0.175,
      0.001556
    ],
    [
      0.2,
      0.001556
    ],
    [
      0.225,
      0.001556
    ],
    [
      0.25,
      0.001556
    ],
    [
      0.275,
      0.001556
    ],
    [
      0.3,
      0.001556
    ],
    [
      0.325,
      0.001556
    ],
    [
      0.35,
      0.001556
    ],
    [
      0.375,
      0.001556
    ],
    [
      0.4,
      0.001556
    ],
    [
      0.425,
      0.001556
    ],
    [
      0.45,
      0.003745
    ],
    [
      0.475,
      0.003745
    ],
    [
      0.5,
      0.003745
    ],
    [
      0.525,
      0.003745
    ],
    [
      0.55,
      0.0131
    ],
    [
      0.575,
      0.013575
    ],
    [
      0.6,
      0.013575
    ],
    [
      0.625,
      0.020708
    ],
    [
      0.65,
      0.020708
    ],
    [
      0.675,
      0.020708
    ],
    [
      0.7,
      0.020708
    ],
    [
      0.725,
      0.020708
    ],
    [
      0.75,
      0.020708
    ],
    [
      0.775,
      0.020708
    ],
    [
      0.8,
      0.020708
    ],
    [
      0.825,
      0.020708
    ],
    [
      0.85,
      0.030769
    ],
    [
      0.875,
      0.033426
    ],
    [
      0.9,
      0.033426
    ],
    [
      0.925,
      0.033426
    ],
    [
      0.95,
      0.033426
    ],
    [
      0.975,
      0.079545
    ],
    [
      1.0,
      0.111111
    ]
  ],
  "baseRate": 0.013666
} as const satisfies RankingModel;
